/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
var data={
    channels:[{
        id:1,
        title:'اخبار',
        url:'http://www.almasryalyoum.com/rss_feed_term/1/rss.xml',
        unreaditems:0,
        active:true,
        lastItemPubDate:0,
        category:'news'
    },{
        id:2,
        title:'تقارير المراسلين',
        url:'http://www.almasryalyoum.com/rss_feed_term/40703/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:3,
        title:'أخبار مصر',
        url:'http://www.almasryalyoum.com/rss_feed_term/2/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:4,
        title:'الحوادث',
        url:'http://www.almasryalyoum.com/rss_feed_term/3/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:5,
        title:'الشارع السياسي',
        url:'http://www.almasryalyoum.com/rss_feed_term/4/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:6,
        title:'العالم',
        url:'http://www.almasryalyoum.com/rss_feed_term/5/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:7,
        title:'العالم العربي',
        url:'http://www.almasryalyoum.com/rss_feed_term/6/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:8,
        title:'اقتصاد',
        url:'http://www.almasryalyoum.com/rss_feed_term/7/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:9,
        title:'البورصة',
        url:'http://www.almasryalyoum.com/rss_feed_term/11/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:10,
        title:'الرياضة',
        url:'http://www.almasryalyoum.com/rss_feed_term/14/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:11,
        title:'كرة عالمية',
        url:'http://www.almasryalyoum.com/rss_feed_term/17/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:12,
        title:'كرة عربية',
        url:'http://www.almasryalyoum.com/rss_feed_term/18/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:13,
        title:'كرة مصرية',
        url:'http://www.almasryalyoum.com/rss_feed_term/19/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:14,
        title:'علوم وتكنولوجيا',
        url:'http://www.almasryalyoum.com/rss_feed_term/24/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:15,
        title:'طب وصحة',
        url:'http://www.almasryalyoum.com/rss_feed_term/26/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:16,
        title:'موبايل واتصالات',
        url:'http://www.almasryalyoum.com/rss_feed_term/29/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:17,
        title:'فن وثقافة',
        url:'http://www.almasryalyoum.com/rss_feed_term/30/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:18,
        title:'الناشر',
        url:'http://www.almasryalyoum.com/rss_feed_term/31/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:19,
        title:'تلفزيون',
        url:'http://www.almasryalyoum.com/rss_feed_term/32/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:20,
        title:'سينما',
        url:'http://www.almasryalyoum.com/rss_feed_term/33/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:21,
        title:'فنون',
        url:'http://www.almasryalyoum.com/rss_feed_term/34/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:22,
        title:'ملفات خاصة',
        url:'http://www.almasryalyoum.com/rss_feed_term/36/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:23,
        title:'تحقيقات',
        url:'http://www.almasryalyoum.com/rss_feed_term/37/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:24,
        title:'حوارات',
        url:'http://www.almasryalyoum.com/rss_feed_term/38/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:25,
        title:'ملفات هامه',
        url:'http://www.almasryalyoum.com/rss_feed_term/39/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:26,
        title:'الأخيرة',
        url:'http://www.almasryalyoum.com/rss_feed_term/5238/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:27,
        title:'أخبار الصفحة الأولي',
        url:'http://www.almasryalyoum.com/news_homepage_feed',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    }],
    multimedia:{
        title:"ملتي ميديا",
        active:false,
        video:{
            id:28,
            title:'فيديو',
            url:'http://www.almasryalyoum.com/rss_feed_video/rss.xml',
            unreaditems:0,
            active:false,
            lastItemPubDate:0,
            category:'thumb'
        },
        car:{
            id:29,
            title:'كاريكاتير',
            url:'http://www.almasryalyoum.com/rss_feed_caricature/rss.xml',
            unreaditems:0,
            active:false,
            lastItemPubDate:0,
            category:'thumb'
        }
    }
}
var data_en={
    channels:[{
        id:1,
        title:'News',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/113/rss.xml',
        unreaditems:0,
        active:true,
        lastItemPubDate:0,
        category:'news'
    },{
        id:2,
        title:'Top stories',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/114/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:3,
        title:'News features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/115/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:4,
        title:'Economy',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/120/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:5,
        title:'Economy features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/122/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:6,
        title:'Art',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/133/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:7,
        title:'Cinema',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/134/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:8,
        title:'Local press review',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/147/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:9,
        title:'Media features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/148/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:10,
        title:'Travel features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/153/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:11,
        title:'Economy news',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/186/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:12,
        title:'Environment features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/189/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:13,
        title:'Environment news',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/190/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:14,
        title:'World news',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/192/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:15,
        title:'World features',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/194/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:16,
        title:'Health',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/197/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:17,
        title:'Society',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/199/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:18,
        title:'Fashion',
        url:'http://www.almasryalyoum.com/en/rss_feed_term/200/rss.xml',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    }/*,{
        id:19,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:20,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:21,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:22,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:23,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:24,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:25,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:26,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    },{
        id:27,
        title:'',
        url:'',
        unreaditems:0,
        active:false,
        lastItemPubDate:0,
        category:'news'
    }*/],
    multimedia:{
        title:"multimedia",
        active:false,
        video:{
            id:28,
            title:'video',
            url:'http://www.almasryalyoum.com/en/rss_feed_video/rss.xml',
            unreaditems:0,
            active:false,
            lastItemPubDate:0,
            category:'thumb'
        },
        car:{
            id:29,
            title:'carecater',
            url:'http://www.almasryalyoum.com/en/rss_feed_caricature/rss.xml',
            unreaditems:0,
            active:false,
            lastItemPubDate:0,
            category:'thumb'
        }
    }
}

